version: '3.8'

services:
  inventory-app:
    build: .
    container_name: inventory-app
    restart: unless-stopped
    ports:
      - "100.74.117.90:8000:8000"
    volumes:
      - ./data:/app/data
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - FLASK_DEBUG=False
      - SECRET_KEY=dtwXoTl0YgblWP9ZugXBIUpGPfHwtlfLApf-02HRFWGXPF6U4tvXQjMS00RsOjcyk-E
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge
